server:
  port: 9999
  
spring:
  application:
    name: zuul-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
 
zuul:
  ignoredServices: "*"
  routes:
    results-service:
      path: /results-service/**
      serviceId: results-service
    student-service:
      path: /student-service/**
      service-id: student-service